#include<iostream>
#include<string>
#include<ctime>
#include<time.h>
#include<stdio.h>
#include<stdlib.h>
#include<vector>
#include<chrono>
#include "encryption.h"
#include "newCBSignature.h"
#include "sha256.h"

using namespace std;

#ifndef TRANSACTION_H
#define TRANSACTION_H



class transaction
{

private:
	//stores fromkey as a string by converting matrices to string
	string from;
	//stores tokey as a string by converting matrices to string
	string to;
	//amount of the transaction
	int amount;
	//stores hash information of all of the above stuff
	string hash;
	//stores the from key itself (for new CB signature algorithm)
	newCBPublic fromkey;
	//stores the to key itself (for new CB signature algorithm)
	newCBPublic tokey; 
	//stores the signature (for the new CB Signature algorithm) that this transaction has
	CBSignature2 usedsig;
	//from key for KKS system
	publickey fromkeyKKS;
	//to key for KKS system
	publickey tokeyKKS;
	//signature for KKS system - is just the string omega as generated by the algorithm
	string KKSOmega;
	
	
	
public:
	//0 & 3 arg constructors
	transaction();
	//three argument constructor used to set the public and private keys (if we are using the new CB system) and transaction amount
	transaction(newCBPublic setfrom, newCBPublic setto, int setAmount);
	//three argument constructor used to set the public and private keys (if we are using KKS system) and transaction amount
	transaction(publickey setfrom, publickey setto, int setAmount);
	transaction(string setfrom, string setto, int setAmount);
	//note - I only really use this one in blockchain.minePendingTransactions() function
	//in which case setfrom = "NULL" and setto is the reward address
	//this one is only for the new CB signature
	transaction(string setfrom, newCBPublic setto, int setAmount);
	//this one is only for the KKS signature
	transaction(string setfrom, publickey setto, int setAmount);
	//accessor and mutator functions
	void setFrom(string s);
	void setTo(string t);
	void setAmount(int a);
	void setfromkey(newCBPublic setfrom);
	void settokey(newCBPublic setto);
	string getFrom();
	string getTo();
	int getAmount();
	newCBPublic getfromkey();
	newCBPublic gettokey();
	publickey getfromkeyKKS();
	publickey gettokeyKKS();
	//sets sha 256 hash of this transaction- based on what is stored (fromaddress, toaddress, amount)
	void calculateHash();
	//sign a transaction using method 1 - KKS signature algorithm
	void signTransaction1(publickey usedPublic, privatekey usedPrivate);
	//sign a transaction using method 2 - new CB signature algorithm
	void signTransaction2(newCBPublic usedPublic, newCBPrivate usedPrivate);
	//verify the signature for the transaction using method 1 - KKS signature algorithm
	bool isTransactionValid1();
	//verify the signature for the transaction using method 2 - new CB signature algorithm
	bool isTransactionValid2();
	
	

};



#endif /* TRANSACTION.H */
